{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "infrastore.fullname" . }}-rolebinding
  labels:
    {{- include "labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "infrastore.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "infrastore.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
